- go.mod
- go.sum
- pkg/k8s/secret.go
Set `OwnerReferences` in backup secret to allow cascading delete when the owner service account deleted. 
```console
% kubectl get secret
NAME               TYPE                DATA   AGE
my-backup-secret   kubernetes.io/tls   2      44s
% kubectl delete sa my-sa
serviceaccount "my-sa" deleted
% kubectl get secret
No resources found in default namespace.
```
---
> Set `OwnerReferences` in backup secret metadata

- pkg/identity/certificated.go
While you can modify `ROLECERT_DIR` to change the directory path for generating role certificates using SIA, if the specified directory doesn't exist, the operation will fail.
---
> SIA creates a directory for role certificates if not present

- .github/pull_request_template.md
- pkg/token/athenz.go
- pkg/token/model.go
- refactor access token parse logic
- remove checkbox in PR template
- #30
---
> refactor JWT parse

- pkg/identity/certificated.go
When k8s-athenz-sia is used as sidecar, it should not try to write instance cert, when localBackup is used in the red sqaure.
> Fix So That SIA does NOT Write Instance Cert When Local File Backup Used

- athenz-sia.env
- pkg/config/config.go
- pkg/config/default.go
- pkg/config/model.go
- pkg/token/daemon.go
- pkg/token/server.go
https://github.com/AthenZ/k8s-athenz-sia/issues/80
- Attaching tokens in the header is the de facto standard used by Envoy, nginx and other proxies and therefore there is no needed to clearly define what the feature does. We choose to use the `USE_TOKEN_SERVER` as the token server should attach the token in the header side (world standard)
- https://github.com/AthenZ/k8s-athenz-sia/issues/65
> Fix Env TOKEN_SERVER_ENVOY_API -> USE_TOKEN_SERVER

- go.mod
- go.sum
- pkg/token/cache.go
- pkg/token/daemon.go
- pkg/token/server.go
- pkg/token/type.go
When handling multiple requests for the same token, it's unnecessary to send several requests to the ZTS server in short span. To optimize this, we can utilize the singleflight feature from the golang.org/x/sync/singleflight package, which ensures that for a given token, only one request is made to the ZTS server, and its result is shared across all the requests.
Also, to effectively monitor whether a specific requestID has been processed using singleflight or not, loggers that allow us to determine whether a request was handled directly or if its response was the result of a shared call to the ZTS serve is a must.
*This is the expected log for single request:*
```sh
Attempting to fetch role token due to a cache miss from Athenz ZTS server: target[provider.domain.name], requestID[11111] …
```
> Golang Singleflight for fetching at/rt to zts server

- pkg/token/athenz.go
- pkg/token/server.go
- When obtaining a role token, we have made it so that the maxExpiry set in the request body is ignored.
- If there is any minExpiry that is negative, we have made it so that it will be ignored.
- Closes #_PR_
---
> Disable maxExpiry Option When obtaining a role token

- Makefile
- cmd/athenz-sia/main.go
- pkg/identity/identity.go
- pkg/token/athenz.go
- pkg/version/version.go
Modified request header `User-Agent` to include version of `athenz-sia` when making requests to the ZTS Server.
- `User-Agent: athenz-sia/v3.2.0`
- `athenz-sia` changes depending on binary name.
---
> Add user-agent header to ZTS Server

- athenz-sia.env
- pkg/config/config.go
- pkg/config/default.go
- pkg/config/model.go
- pkg/token/cache.go
- pkg/token/daemon.go
token metrics now includes `k8s_namespace` and `k8s_pod_name` if the following env exists
- `NAMESPACE`
- `POD_NAME`
sample:
```sh
curl -sfS localhost:9793/metrics | grep token | grep token_expires_in_seconds
token_expires_in_seconds{domain="athenz.provider-domain",k8s_namespace="my-namespace",k8s_pod="test-pod-1a2cb7",max_expiry="14400",role="provider-client",type="accesstoken"} 12792.730765255
token_expires_in_seconds{domain="athenz.provider-domain",k8s_namespace="my-namespace",k8s_pod="test-pod-1a2cb7",min_expiry="14400",role="provider-client",type="roletoken"} 12792.730655096
```
> token metrics with k8s namespace and k8s pod name

- athenz-sia.env
- pkg/config/default.go
- Fix default value for BACKUP feature from`"read+write"` to `""` 
- https://github.com/AthenZ/k8s-athenz-sia/issues/90
---
> Modify default value for BACKUP feature

- pkg/token/service.go
TARGET_DOMAIN_ROLES is not a factor to enable/disable token server.
---
> Log not accurate enough

- pkg/util/tls-reload.go
`r.pollRefresh()` must run only when the following condition all met:
- `config.ProviderService == ""`
- `config.CertFile != ""`
- `config.KeyFile != ""`
But current code only checks `config.ProviderService == ""`, and it is a bug.
Reference: 
- https://github.com/AthenZ/k8s-athenz-sia/blob/main/pkg/certificate/service.go#L188
- https://github.com/AthenZ/k8s-athenz-sia/blob/main/pkg/certificate/service.go#L199
```
```
---
```
```
```
```
> Fix condition for `r.pollRefresh()`

- pkg/token/service.go
- issue: writing to token file will keep failing if token DIR not exists
- changes: create token DIR if not exists
```
```
---
```
```
```
```
> Create token DIR if not exists

- cmd/athenz-sia/main.go
log filename should follow the binary filename, instead of using a hard-coded value
```
```
---
> log filename follows the binary filename

- pkg/token/cache.go
- pkg/token/server.go
- pkg/token/service.go
Updated the internal logic of the function that outputs Access Tokens and Role Tokens to files.
The process of updating the memory cache for each token will also include file output processing. This will result in the following:
- File output and retry processing will be performed for each token.
- File output processing will be executed in parallel.
```
```
---
```
```
```
```
> Writing Token Files Update Individually with Go Routine

- pkg/util/path-generator.go
- pkg/util/path-generator_test.go
To address https://github.com/AthenZ/k8s-athenz-sia/issues/49, we created a module that outputs customizable file names (with directories) for RoleCert, AccessTokens and RoleTokens. The module is not yet used but will be integrated in the next pull request. The actual environment configurations will be also included in future PRs later.
```
```
---
```
```
```
```
> Add Path Generator

- pkg/certificate/identity.go
- pkg/certificate/service.go
- pkg/config/config.go
- pkg/config/default.go
- pkg/config/derived-access-token.go
- pkg/config/derived-role-cert.go
- pkg/config/dervied.go
- pkg/config/model.go
- pkg/metrics/service.go
Refactor RoleCert feature with DerivedState.
Related Issue: https://github.com/AthenZ/k8s-athenz-sia/issues/113
```
```
---
```
```
```
```
> Role cert with derived state and its new config

- pkg/config/derived-role-cert.go
Fixed an issue where specifying a path without a trailing slash (e.g., '/var/run/athenz') in ROLECERT_DIR would result in the directory not being created correctly.
This was introduced in: https://github.com/AthenZ/k8s-athenz-sia/pull/142
```
```
---
```
```
```
```
> Fix Derived RoleCert Dir

- pkg/config/config.go
- pkg/config/derived-role-cert.go
- pkg/config/derived-target-domain-roles.go
- pkg/config/dervied.go
- pkg/config/model.go
The current code has function `parseTargetDomainRoles` out of nowhere.
Refactor with derived state for easier read.
```
```
---
```
```
```
```
> Refactor parseTargetDomainRoles with derived state `DerivedRoleCert`

- pkg/config/derived-token-file.go
- pkg/token/service.go
Refactored derivedTokenFIleConfig() to utilize the function GeneratePath() introduced in https://github.com/AthenZ/k8s-athenz-sia/pull/141
Also has added some comments for TODOs
```
```
---
```
```
```
```
> Refactor derived-token-file with `Format`

- pkg/token/server.go
Modify the system to temporarily not output INFO logs for each Token retrieval request from clients. 
- For clients with a high number of requests, the volume of logs can become enormous, potentially affecting performance and log collection.
```
```
---
```
```
```
```
> remove access info log

- pkg/healthcheck/service.go
- pkg/metrics/service.go
- pkg/token/service.go
Fix of the following error. There are 2 issues causing the problem which are listed as below.
```log
WARNING[2024-11-28T18:09:07+09:00] Failed to confirm the server ready with GET request: Get "https://localhost:22408/": http: server gave HTTP response to HTTPS client. Retrying in 44.115047941s
ERROR[2024-11-28T18:09:52+09:00] Failed to confirm token provider server ready: Get "https://localhost:22408/": http: server gave HTTP response to HTTPS client
ERROR[2024-11-28T18:09:52+09:00] Error starting token provider: Get "https://localhost:22408/": http: server gave HTTP response to HTTPS client
...
INFO[2024-11-28T18:09:52+09:00] Initiating shutdown by cause: start failed: Get "https://localhost:22408/": http: server gave HTTP response to HTTPS client ...
INFO[2024-11-28T18:09:52+09:00] …
```
> prevent race condition in http.Server.TLSConfig and deadlock in shutdown

- pkg/config/config.go
We have modified the system so that when starting in init mode, it no longer performs a size comparison between the TokenRefresh and TokenExpiry settings at startup. 
- The size comparison between TokenRefresh and TokenExpiry is a logic used to prevent the token from expiring before the cache is updated when starting in refresh mode. Therefore, it is not necessary to execute the above comparison and validation logic in init mode.
```
```
---
```
```
```
```
> Modify the logic to validate the size comparison between the token's expiration time and refresh frequency so that it is executed only in init mode

- .github/workflows/docker-build-publish.yaml
- pkg/metrics/service.go
- from: [v3.17.0](https://github.com/enix/x509-certificate-exporter/commits/v3.17.0), `8f97b98` => current version used in by SIA `c0ca500` => [v3.18.0](https://github.com/enix/x509-certificate-exporter/commits/v3.18.0), `476b093` => [v3.18.1](https://github.com/enix/x509-certificate-exporter/commits/v3.18.1), `e2f8c412`
- releases: https://github.com/enix/x509-certificate-exporter/releases
- [related changes](https://github.com/enix/x509-certificate-exporter/pull/287/files#diff-5e3b74e65c364421f5a4e20512bfc447cfedc75d2734716d740f22f4b2fb3226R995)
- upgrade `actions/upload-artifact@v3` and `actions/download-artifact@v3` => `v4`
- [Deprecation notice: v3 of the artifact actions - GitHub Changelog](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/)
- …
> Upgrade x509-certificate-exporter to v3.18.1 and upload/download-artifact to v4

- pkg/config/derived-k8s-secret-backup.go
- pkg/config/derived-role-cert.go
- pkg/config/derived-service-cert.go
- pkg/config/derived-target-domain-roles.go
- pkg/config/derived-token-file.go
- pkg/config/derived-token-server.go
- pkg/config/dervied.go
as title, package comment is written in `doc.go` already
https://github.com/AthenZ/k8s-athenz-sia/blob/8af30bdec5271c8fe725aef6b3c1efeaf8d19ea5/pkg/config/doc.go#L15-L16
- [x Apply one or more `labels` of the following that fits:
```
```
---
```
```
```
```
> remove duplicated package comments
