.gitignore
pkg/k8s/secret.go

Added "Force: true" to metav1.ApplyOptions

---

cmd/athenz-sia/main.go

Fixed Role Certificate file name

---

.github/workflows/docker-build-publish.yaml
.github/workflows/github-releases.yaml

Fixed docker-build-publish.yaml

---

pkg/identity/identity.go

Fixed concatenation for instance identity certificate

---

.github/workflows/docker-build-publish.yaml
.github/workflows/trigger-workflows.yaml
README.md

- add container push variable in pipeline
- #13
---

add container push variable in pipeline

---

cmd/athenz-sia/main.go
pkg/identity/certificated.go
pkg/identity/identity.go
pkg/identity/metricsd.go
pkg/identity/tokend.go

K8s secret backup improvements

---

pkg/identity/tokend.go

1. cannot get token from cache
2. cannot save token as file
---

tokend bugfix

---

docs/development/sia-goroutine-and-channel.md

add dev doc: [k8s-athenz-sia/docs/development/sia-goroutine-and-channel.md at 9e5504fa020f47e6967154a76690832ada18def9 · WindzCUHK/k8s-athenz-sia](https://github.com/WindzCUHK/k8s-athenz-sia/blob/9e5504fa020f47e6967154a76690832ada18def9/docs/development/sia-goroutine-and-channel.md)
---

add dev doc

---

pkg/identity/identity.go

Update PostRoleCertificateRequest endpoint
- Closes #_PR_
---

Update PostRoleCertificateRequest endpoint

---

.github/pull_request_template.md
.gitignore
.licenserc.yaml
CONTRIBUTING.md
MAINTAINERS
README.md
cmd/athenz-sia/main.go
pkg/config/config.go
pkg/config/default.go
pkg/config/doc.go
pkg/config/model.go
pkg/identity/certificated.go
pkg/identity/healthcheckd.go
pkg/identity/identity.go
pkg/identity/metricsd.go
pkg/k8s/secret.go
pkg/token/athenz.go
pkg/token/cache.go
pkg/token/daemon.go
pkg/token/doc.go
pkg/token/model.go
pkg/token/server.go
pkg/token/sidecar.gen.go
pkg/token/tls.go
pkg/token/type.go
pkg/util/athenz.go
pkg/util/athenz_test.go

- `Yahoo Japan Corporation` => `LY Corporation`
- update maintainers list
---

Fix for corporation name and maintainers changes

---

athenz-sia.env

- Specify default value for binary
- Provide the URL where the default value is set
- Adjust the order of environment variables to match [config.go](https://github.com/AthenZ/k8s-athenz-sia/blob/main/pkg/config/config.go)
- Closes #_PR_
---

fix athenz-sia.env

---

athenz-sia.env

Fix 404 hash. Please merge together with next PR.
---

Update athenz-sia.env ROLE_CERT_KEY_FILE_OUTPUT

---

.github/workflows/docker-build-publish.yaml
.github/workflows/github-releases.yaml
.github/workflows/go-test.yaml
.github/workflows/trigger-workflows.yaml

as title
- fix typo
- rename `DOCKER_REGISTRY_OWNER` => `DOCKER_REGISTRY_ORG`
- split `DOCKER_REGISTRY_USER`
---

move docker registry login values to repository environment

---

go.sum
pkg/token/cache.go
pkg/token/daemon.go

Add token_expires_in_seconds metrics
```bash
$ curl -sfS localhost:9793/metrics | grep 'token_expires_in_seconds'
token_expires_in_seconds{domain="domain1",role="role1",type="roletoken"} 14120.64295
token_expires_in_seconds{domain="domain1",role="role1",type="accesstoken"} 12754.642959
token_expires_in_seconds{domain="domain2",role="role2",type="roletoken"} 12754.642952
```
```bash
$ curl -sfS localhost:9793/metrics | grep 'token_expires_in_seconds'
token_expires_in_seconds{domain="domain",role="users",type="roletoken"} 13877.364748
token_expires_in_seconds{domain="domain",max_expiry="10000",role="role",type="roletoken"} 9510.364777
token_expires_in_seconds{domain="domain",min_expiry="10000",role="role",type="roletoken"} 13923.364768 …
```

Add token expiry metrics

---

cmd/athenz-sia/main.go

Add build_info log and  metrics
```
INFO[2024-03-05T11:05:41+09:00] starting athenz-sia version: 915c51b, build date: 2024-03-04T14:11:11JST+0900
```
```
$ curl -sf -X GET http://localhost:9793/metrics
build_info{app_name="athenz-sia",build_date="2024-03-04T14:11:11JST+0900",version="915c51b"} 1
```
- Closes #_PR_
---

Add build_info log and  metrics

---

pkg/config/config.go
pkg/config/default.go
pkg/config/doc.go
pkg/config/model.go
pkg/identity/certificated.go
pkg/identity/healthcheckd.go
pkg/identity/identity.go
pkg/identity/metricsd.go
pkg/token/daemon.go
pkg/token/server.go

Error handling improvement

---

pkg/token/cache.go
pkg/token/daemon.go

- remove package dependency
- from: https://github.com/AthenZ/k8s-athenz-sia/pull/103
---

cache.go minor refactoring

---

Makefile
cmd/athenz-sia/main.go
pkg/certificate/identity.go
pkg/certificate/service.go
pkg/config/config.go
pkg/config/runtime-constant.go
pkg/daemon/daemon.go
pkg/healthcheck/service.go
pkg/metrics/service.go
pkg/token/athenz.go
pkg/token/service.go

Unify variable name as `idCfg` and create `USER_AGENT` constant

---

docs/development/mode=refresh-sequence.md

fix typo
```
```
---
```
```
```
```

fix development doc

---

cmd/athenz-sia/main.go
pkg/config/default.go

Add a process to check the configuration of logDiradd logDir check

---

README.md

Remove the duplicate release icons

---

pkg/token/service.go

I found logically wrongful comment 
```
```
---
```
```
```
```

Comment fixed

---

pkg/token/service.go

The content of the log output when obtaining a token has been adjusted to match the specifications for obtaining a Role Cert.
```
```
---
```
```
```
```

Fix Save Token Log

---

pkg/certificate/identity.go
pkg/certificate/service.go
pkg/config/config.go
pkg/config/default.go
pkg/config/derived-k8s-secret-backup.go
pkg/config/dervied.go
pkg/config/model.go

Refactor Backup Related State
Related issue: https://github.com/AthenZ/k8s-athenz-sia/issues/113#issuecomment-2348446481
```
```
---
```
```
```
```

Refactor Backup Related State

---

pkg/token/server.go
pkg/token/service.go

Remove unnecessary configurations for the TokenServer from service.go
```
```
---
```
```
```
```

Remove unnecessary configurations for the TokenServer from service.go

---

pkg/certificate/identity.go

For availability, the role certificate expiry should be reasonably long. For non-CopperArgos cases, when the external certificate is short-lived (< 24h), the role certificate issued may expire before the default refreshing cycle (24h). 
```
```
---
```
```
```
```

issue role certificate with Athenz server default expiry for non-CopperArgos cases

---

.github/workflows/docker-build-publish.yaml

as title, fix issue in #182 
required changes: https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md
```
```
---
```
```
```
```

fix github action issue in #182

---

.github/workflows/github-releases.yaml
.github/workflows/go-test.yaml
.github/workflows/lint.yaml
.github/workflows/trigger-workflows.yaml
.golangci.yml
.remarkrc
Makefile

- golangci-lint: lint go files
- [Configuration | golangci-lint](https://golangci-lint.run/usage/configuration/#severity-configuration)
- markdownlint: lint markdown files
- [remark/doc/plugins.md at main · remarkjs/remark](https://github.com/remarkjs/remark/blob/main/doc/plugins.md#list-of-plugins)
- codecov: upload and compare unit test coverage
- https://app.codecov.io/gh/AthenZ/k8s-athenz-sia/tree/add-linters
- [repo setting](https://github.com/AthenZ/k8s-athenz-sia/settings/security_analysis#:~:text=Disable-,Code%20scanning,-Automatically%20detect%20common)
- [scan result](https://github.com/AthenZ/k8s-athenz-sia/security/code-scanning)
- `good first issue`: …

add linter
